//
// CatFact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** CatFact */
public struct CatFact: Codable, JSONEncodable, Hashable {

    /** Fact */
    public var fact: String?
    /** Length */
    public var length: Int?

    public init(fact: String? = nil, length: Int? = nil) {
        self.fact = fact
        self.length = length
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fact
        case length
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fact, forKey: .fact)
        try container.encodeIfPresent(length, forKey: .length)
    }
}

